name: Release (NPM)

on:
  push:
    tags: ["v*.*.*"]

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  release:
    name: Publish to npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 11

      - uses: actions/setup-node@v4
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'
          package-manager-cache: false  # never use caching in release builds

      - run: pnpm install --frozen-lockfile
      - run: pnpm build

      - name: Stage publish to npm
        run: npm stage publish
