name: Release (JSR)

on:
  push:
    tags: ["v*.*.*"]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  publish:
    name: Publish to JSR
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - name: Publish package
        run: npx jsr publish
